apiVersion: v1
kind: Secret
metadata:
  name: influxdb
  labels:
    app: influxdb
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: password
  INFLUXDB_DB: telegraf
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: password
